# Generated by cucumber-sinatra. (2015-03-10 11:16:07 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/blogbook.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Blogbook

class BlogbookWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BlogbookWorld.new
end
